# Copyright 2026 National Payments Corporation of India
# SPDX-License-Identifier: MIT

"""API Registry — canonical, deterministic store of network wire-API specs.

One row per message (``ReqTransfer``, ``RespActivation``, …) plus one row per
tag/attribute with its documented constraints (occurrence, datatype, length,
mandatory, rules). The TSD ``interface_spec`` field dictionaries are RENDERED
from these rows instead of re-generated by the LLM — same rows in, identical
table out.

Provenance model: every field row records per-source evidence in
``constraint_sources`` (``{"xsd": {...}, "code": {...}, "manual": {...}}``).
Structural facts come from the deterministic XSD parse; code-harvested
constraints land as evidence with file:line and never silently overwrite a
human edit (``updated_by`` set ⇒ the row's canonical values are locked).
"""
from datetime import datetime

from sqlalchemy import String, Text, Integer, Boolean, ForeignKey, JSON, DateTime
from sqlalchemy.orm import mapped_column, Mapped, relationship

from app.core.database import Base
from app.models.base import TimestampMixin, generate_uuid


class ApiMessage(Base, TimestampMixin):
    __tablename__ = "api_messages"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    api_name: Mapped[str] = mapped_column(String(200), nullable=False, unique=True, index=True)
    # "request" | "response" | "other" — derived from the Req/Resp prefix.
    direction: Mapped[str] = mapped_column(String(20), nullable=False, default="other")
    namespace: Mapped[str | None] = mapped_column(String(500), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Deterministically generated skeleton XML (enums inline), regenerated on ingest.
    sample_xml: Mapped[str | None] = mapped_column(Text, nullable=True)
    # "xsd_parse" | "manual" | change_request id that introduced it.
    source: Mapped[str] = mapped_column(String(60), nullable=False, default="xsd_parse")
    source_schema_path: Mapped[str | None] = mapped_column(String(1000), nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    introduced_by_change_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    updated_by: Mapped[str | None] = mapped_column(String(200), nullable=True)

    fields: Mapped[list["ApiField"]] = relationship(
        "ApiField", back_populates="message", cascade="all, delete-orphan",
        order_by="ApiField.position",
    )


class ApiField(Base, TimestampMixin):
    __tablename__ = "api_fields"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=generate_uuid)
    message_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("api_messages.id", ondelete="CASCADE"), nullable=False, index=True
    )
    parent_field_id: Mapped[str | None] = mapped_column(
        String(36), ForeignKey("api_fields.id", ondelete="CASCADE"), nullable=True
    )
    # Document order across the whole message (depth-first), drives rendering.
    position: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    depth: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # The Authority-style hierarchical numbering ("2.1.1"). Deterministic, regenerated on ingest.
    tag_num: Mapped[str | None] = mapped_column(String(30), nullable=True)
    # Element name, or attribute name when is_attribute.
    xml_tag: Mapped[str] = mapped_column(String(200), nullable=False)
    is_attribute: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    # Stable join key: "ReqTransfer/Head/@ver". Unique within a message.
    xpath: Mapped[str] = mapped_column(String(1000), nullable=False)

    # ── The documented constraint columns (the TSD table cells) ──
    message_item: Mapped[str | None] = mapped_column(Text, nullable=True)      # prose description
    occurrence: Mapped[str | None] = mapped_column(String(20), nullable=True)  # "1..1", "0..n"
    datatype: Mapped[str | None] = mapped_column(String(60), nullable=True)
    length_rule: Mapped[str | None] = mapped_column(String(200), nullable=True)
    mandatory: Mapped[str | None] = mapped_column(String(5), nullable=True)    # "Y" | "N" | "C"
    condition_text: Mapped[str | None] = mapped_column(Text, nullable=True)    # when mandatory == "C"
    rules_ref: Mapped[str | None] = mapped_column(String(500), nullable=True)  # e.g. "019_Head_Version"
    # Human-entered validation regex (tier-3) — the fallback when XSD/code harvest
    # miss a constraint. Evidence-grade, editable + lockable like the other cells.
    pattern_rule: Mapped[str | None] = mapped_column(String(500), nullable=True)
    enum_values: Mapped[list | None] = mapped_column(JSON, nullable=True)

    # Per-source evidence: {"xsd": {...}, "code": {file,line,snippet,commit}, "manual": {...}}
    constraint_sources: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    source: Mapped[str] = mapped_column(String(60), nullable=False, default="xsd_parse")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")
    introduced_by_change_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # Set on human edit — locks canonical values against ingest overwrite.
    updated_by: Mapped[str | None] = mapped_column(String(200), nullable=True)

    message: Mapped["ApiMessage"] = relationship("ApiMessage", back_populates="fields")
