# Copyright 2026 National Payments Corporation of India
# SPDX-License-Identifier: MIT

"""Git Integrator Service.

Pushes approved code to GitLab: create feature branch → commit files → raise MR.
Merging is a HUMAN action — the agent never merges (§22).
Uses real GitLab API (python-gitlab) when GITLAB_URL and GITLAB_TOKEN are configured.
Falls back to simulation when GitLab is not available.

M-4 (2026-05-04) — multi-repo support:
  - `push_to_gitlab` now groups files by `repo_id` (set by the M-3 parser
    on each file dict). One MR is opened per repo, all on the same shared
    branch name (M-2 default).
  - `phase_b_run_repos` rows are populated with mr_url / mr_iid / mr_state
    per repo so the UI can render a list of MRs.
  - Each repo also gets its own `git_events` row for back-compat with the
    legacy single-MR display.
  - The final returned `GitEvent` is the FIRST repo's event (legacy display),
    but the full per-repo result list is returned alongside via a new
    `push_to_gitlab_multi` entry point.
"""
import asyncio
import hashlib
import logging
import secrets

from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.base import generate_uuid, utcnow
from app.models.phase_b import (
    PhaseBRun, PhaseBRunRepo, PhaseBStep, GitEvent, GitEventStatus,
)
from app.models.code_repo import CodeRepo

logger = logging.getLogger(__name__)


def _has_gitlab_config() -> bool:
    return bool(settings.gitlab_url and settings.gitlab_token)


def _public_gitlab_url() -> str:
    """URL for display in the UI (use localhost, not host.docker.internal)."""
    url = settings.gitlab_url or ""
    return url.replace("host.docker.internal", "localhost").rstrip("/")


def _random_sha() -> str:
    return secrets.token_hex(20)


def content_hash(files: list[dict]) -> str:
    """Order-independent sha256 of a files payload — the Phase-B analogue of the
    agentic ``pushed_manifest_hash``: binds "pushed" to WHAT was pushed, so an
    unchanged payload is idempotent while a re-approved fix round re-pushes."""
    h = hashlib.sha256()
    for f in sorted(files or [], key=lambda x: x.get("path") or ""):
        h.update((f.get("path") or "").encode("utf-8"))
        h.update(b"\x00")
        h.update((f.get("content") or "").encode("utf-8"))
        h.update(b"\x01")
    return h.hexdigest()


# ── Real GitLab integration ──────────────────────────────────────────────────

def _get_gitlab_project(repo: str):
    """Get a python-gitlab Project object."""
    import gitlab as gl_module
    gitlab_url = settings.gitlab_url or ""
    if "://localhost" in gitlab_url:
        gitlab_url = gitlab_url.replace("://localhost", "://host.docker.internal")
    glab = gl_module.Gitlab(gitlab_url, private_token=settings.gitlab_token, keep_base_url=True)
    return glab.projects.get(repo)


def _real_create_branch(project, branch_name: str, base_branch: str) -> None:
    """Create a feature branch from base branch."""
    try:
        project.branches.create({"branch": branch_name, "ref": base_branch})
        logger.info("GitLab — created branch %s from %s", branch_name, base_branch)
    except Exception as e:
        # Branch may already exist from a previous attempt
        if "already exists" in str(e).lower() or "Branch already exists" in str(e):
            logger.info("GitLab — branch %s already exists, reusing", branch_name)
        else:
            raise


def _real_commit_files(project, branch_name: str, files: list[dict], change_id: str) -> str:
    """Commit all files to the branch in a single commit. Returns commit SHA."""
    actions = []
    for f in files:
        # Check if file exists on the branch to decide create vs update
        try:
            project.files.get(file_path=f["path"], ref=branch_name)
            action = "update"
        except Exception:
            action = "create"

        actions.append({
            "action": action,
            "file_path": f["path"],
            "content": f["content"],
        })

    commit = project.commits.create({
        "branch": branch_name,
        "commit_message": f"feat: AI-generated code changes for change request {change_id[:8]}\n\nGenerated by the Authority Change Management Platform",
        "actions": actions,
    })

    sha = commit.id
    logger.info("GitLab — committed %d files, sha=%s", len(files), sha[:12])
    return sha


def _real_create_mr(project, branch_name: str, base_branch: str, change_id: str) -> tuple[str, int]:
    """Create a Merge Request. Returns (mr_url, mr_iid). Reuses existing open MR if one exists."""
    # Check for existing open MR for this source branch
    existing_mrs = project.mergerequests.list(
        source_branch=branch_name,
        target_branch=base_branch,
        state="opened",
    )
    if existing_mrs:
        mr = existing_mrs[0]
        public_url = f"{_public_gitlab_url()}/{project.path_with_namespace}/-/merge_requests/{mr.iid}"
        logger.info("GitLab — reusing existing MR !%d: %s", mr.iid, public_url)
        return public_url, mr.iid

    mr = project.mergerequests.create({
        "source_branch": branch_name,
        "target_branch": base_branch,
        "title": f"feat: Change request {change_id[:8]} — AI-generated code",
        "description": (
            f"## Change Request\n"
            f"ID: `{change_id}`\n\n"
            f"This MR was automatically created by the Authority Change Management Platform.\n"
            f"Code was generated by AI, reviewed, and approved."
        ),
        "remove_source_branch": True,
    })
    public_url = f"{_public_gitlab_url()}/{project.path_with_namespace}/-/merge_requests/{mr.iid}"
    logger.info("GitLab — created MR !%d: %s", mr.iid, public_url)
    return public_url, mr.iid


# ── Multi-repo push (M-4) ────────────────────────────────────────────────────


async def _push_one_repo(
    run: PhaseBRun,
    code_repo: CodeRepo,
    branch_name: str,
    files: list[dict],
    db: Session,
) -> dict:
    """Push one repo's files and open one MR. Persists a GitEvent + updates
    the phase_b_run_repos row for this (run, repo) pair.

    Returns a dict shaped for the caller's response aggregation:
        {repo_id, label, gitlab_repo, branch, mr_url, mr_iid, mr_state,
         commit_sha, files_count, status, error}
    `error` is None on success; otherwise a string and `mr_url`/`mr_iid` are None.
    """
    change_id = run.change_request_id
    repo = code_repo.gitlab_repo
    base_branch = code_repo.gitlab_branch or "main"
    use_real = _has_gitlab_config()

    result = {
        "repo_id":     code_repo.id,
        "label":       code_repo.label,
        "gitlab_repo": repo,
        "branch":      branch_name,
        "files_count": len(files),
        "mr_url":      None,
        "mr_iid":      None,
        "mr_state":    None,
        "commit_sha":  None,
        "status":      None,
        "error":       None,
    }

    if not files:
        # No files routed to this repo — common when one repo wasn't touched
        # by the iteration. Skip cleanly without creating empty MRs.
        logger.info(
            "GitIntegrator — repo=%s has 0 files for run=%s, skipping",
            repo, run.id,
        )
        result["status"] = "skipped_empty"
        return result

    # Never commit to the repo's base branch. The "branch already exists" swallow
    # in _real_create_branch otherwise turns a missing feature branch into a direct
    # commit onto main + a main→main MR attempt — silently.
    if branch_name == base_branch:
        logger.error(
            "GitIntegrator — refusing push for repo=%s: branch %r IS the base branch",
            repo, branch_name,
        )
        result["error"] = (f"refusing to push: branch '{branch_name}' is the repo's "
                           "base branch — set a feature branch first")
        result["status"] = "failed"
        return result

    pbrr = (
        db.query(PhaseBRunRepo)
        .filter(
            PhaseBRunRepo.run_id == run.id,
            PhaseBRunRepo.repo_id == code_repo.id,
        )
        .first()
    )
    files_hash = content_hash(files)
    # Idempotent per repo, bound to CONTENT (agentic pushed_manifest_hash parity):
    # skip only when THIS payload is what the branch already holds. NULL hash =
    # legacy row (unknown) → skip, never surprise-re-push historical runs.
    if pbrr is not None and pbrr.mr_url and (
        pbrr.pushed_content_hash is None or pbrr.pushed_content_hash == files_hash
    ):
        logger.info(
            "GitIntegrator — repo=%s already pushed on %s at %s content, skipping",
            repo, pbrr.branch,
            "an UNKNOWN (legacy row)" if pbrr.pushed_content_hash is None else "the CURRENT",
        )
        result.update({
            "mr_url":   pbrr.mr_url,
            "mr_iid":   pbrr.mr_iid,
            "mr_state": pbrr.mr_state,
            "status":   "already_pushed",
        })
        return result

    logger.info(
        "GitIntegrator — %s push for change=%s, repo=%s, %d files, branch=%s",
        "real" if use_real else "simulated", change_id, repo, len(files), branch_name,
    )

    # Per-repo GitEvent row (back-compat with single-MR UI). The UI's "git/latest"
    # endpoint will return the FIRST repo's event; M-5 adds a multi-repo array.
    git_event = GitEvent(
        id=generate_uuid(),
        phase_b_run_id=run.id,
        branch_name=branch_name,
        status=GitEventStatus.BRANCH_CREATED,
        created_at=utcnow(),
    )
    db.add(git_event)
    db.commit()
    db.refresh(git_event)

    project = None
    try:
        if use_real:
            project = await asyncio.to_thread(_get_gitlab_project, repo)
            await asyncio.to_thread(_real_create_branch, project, branch_name, base_branch)
        else:
            await asyncio.sleep(0.4)

        # Commit
        if use_real:
            commit_sha = await asyncio.to_thread(
                _real_commit_files, project, branch_name, files, change_id,
            )
        else:
            commit_sha = _random_sha()
            await asyncio.sleep(0.4)

        git_event.commit_sha = commit_sha
        git_event.status = GitEventStatus.COMMITTED
        db.commit()

        # MR
        if use_real:
            mr_url, mr_iid = await asyncio.to_thread(
                _real_create_mr, project, branch_name, base_branch, change_id,
            )
        else:
            mr_iid = secrets.randbelow(9900) + 100
            mr_url = f"{_public_gitlab_url()}/{repo}/-/merge_requests/{mr_iid}"
            await asyncio.sleep(0.4)

        git_event.mr_url = mr_url
        git_event.mr_iid = mr_iid
        git_event.status = GitEventStatus.MR_RAISED
        db.commit()

        # Update the phase_b_run_repos row for this (run, repo) pair.
        if pbrr is None:
            # Run was started before M-2 (no phase_b_run_repos rows exist),
            # OR this repo wasn't in the start payload — backfill defensively
            # so M-5's UI still has something to show.
            pbrr = PhaseBRunRepo(
                id=generate_uuid(),
                run_id=run.id,
                repo_id=code_repo.id,
                branch=branch_name,
            )
            db.add(pbrr)
        pbrr.mr_url = mr_url
        pbrr.mr_iid = mr_iid
        pbrr.mr_state = "opened"
        pbrr.pushed_content_hash = files_hash   # bind push state to the pushed content
        pbrr.updated_at = utcnow()
        db.commit()

        result.update({
            "mr_url":      mr_url,
            "mr_iid":      mr_iid,
            "mr_state":    "opened",
            "commit_sha":  commit_sha,
            "status":      git_event.status.value,
        })
        return result

    except Exception as e:
        logger.exception(
            "GitIntegrator — push to repo=%s failed: %s", repo, e,
        )
        # Mark the GitEvent row so the operator can see partial state.
        git_event.status = GitEventStatus.BRANCH_CREATED  # last successful step
        db.commit()
        result["error"]  = f"{type(e).__name__}: {e}"
        result["status"] = "failed"
        return result


async def push_to_gitlab_multi(
    run: PhaseBRun,
    files: list[dict],
    db: Session,
) -> dict:
    """Multi-repo push entry point. Groups files by `repo_id` and opens
    one MR per repo. Use this when the run has a populated
    `phase_b_run_repos` set; falls through to single-repo logic otherwise.

    Args:
        run:   The PhaseBRun (must be at GIT step).
        files: List of {path, content, repo_id} dicts from the latest
               approved iteration. `repo_id` is set by the M-3 parser.
        db:    SQLAlchemy session.

    Returns:
        {
          "branch":  shared branch name used across repos,
          "results": [<per-repo dicts as returned by _push_one_repo>],
          "summary": "<short human-readable status>",
        }
    """
    change_id = run.change_request_id

    # Determine the scoped repos for this run (M-2 schema) + branch.
    repos = (
        db.query(PhaseBRunRepo, CodeRepo)
        .join(CodeRepo, CodeRepo.id == PhaseBRunRepo.repo_id)
        .filter(PhaseBRunRepo.run_id == run.id)
        .order_by(CodeRepo.label)
        .all()
    )

    # Branch name: shared across repos. Use the first phase_b_run_repos
    # row's branch (all rows share the same value when M-2 inserts them).
    if repos:
        branch_name = repos[0][0].branch
    else:
        # Legacy run without phase_b_run_repos — fall through to single-repo.
        branch_name = run.gitlab_branch or settings.gitlab_branch or "main"
        if not branch_name.startswith(("feature/", "change-")):
            branch_name = f"feature/change-{change_id[:8]}"

    # Group files by repo_id; files with no repo_id (legacy) all go to the
    # primary repo (first in the list).
    files_by_repo: dict[str | None, list[dict]] = {}
    for f in files:
        files_by_repo.setdefault(f.get("repo_id"), []).append(f)

    if not repos:
        # ── Legacy single-repo path ──────────────────────────────────────
        # Run was started before M-2; resolve the singular gitlab_repo to
        # a CodeRepo row and push everything there.
        code_repo = (
            db.query(CodeRepo)
            .filter(CodeRepo.gitlab_repo == run.gitlab_repo)
            .first()
        )
        if code_repo is None:
            raise RuntimeError(
                f"Cannot push: legacy run has no phase_b_run_repos rows AND "
                f"gitlab_repo={run.gitlab_repo!r} is not registered in code_repos."
            )
        result = await _push_one_repo(run, code_repo, branch_name, files, db)
        # Advance only on an actual push — a failed push must not move the
        # pipeline to BUILD (it previously advanced unconditionally).
        if result["status"] in (GitEventStatus.MR_RAISED.value, "already_pushed"):
            run.current_step = PhaseBStep.BUILD
            db.commit()
        return {
            "branch":  branch_name,
            "results": [result],
            "summary": _summarise([result]),
        }

    # ── Multi-repo path ──────────────────────────────────────────────────
    # Files with unknown repo_id (LLM forgot to prefix AND path didn't match)
    # default to the FIRST repo. The parser already attempts to assign
    # primary_repo_id in this case, so this is a defensive backstop.
    primary_repo_id = repos[0][1].id
    for f in files:
        if not f.get("repo_id"):
            f["repo_id"] = primary_repo_id

    results: list[dict] = []
    for pbrr, code_repo in repos:
        repo_files = [f for f in files if f.get("repo_id") == code_repo.id]
        result = await _push_one_repo(
            run, code_repo, pbrr.branch, repo_files, db,
        )
        results.append(result)

    # Advance pipeline to BUILD only when EVERY repo with files landed (pushed now
    # or already pushed). A partial failure must not advance — it previously moved
    # to BUILD with some repos never pushed, recorded only in the summary string.
    ok_statuses = {GitEventStatus.MR_RAISED.value, "already_pushed"}
    any_success = any(r["status"] in ok_statuses for r in results)
    any_failed = any(r["status"] == "failed" for r in results)
    if any_success and not any_failed:
        run.current_step = PhaseBStep.BUILD
        db.commit()

    logger.info(
        "GitIntegrator — multi-repo push complete: change=%s branch=%s repos=%d "
        "successes=%d failures=%d skipped=%d",
        change_id, branch_name, len(results),
        sum(1 for r in results if r["status"] == GitEventStatus.MR_RAISED.value),
        sum(1 for r in results if r["status"] == "failed"),
        sum(1 for r in results if r["status"] == "skipped_empty"),
    )

    return {
        "branch":  branch_name,
        "results": results,
        "summary": _summarise(results),
    }


def _summarise(results: list[dict]) -> str:
    """Short human-readable summary of multi-repo push state."""
    parts = []
    for r in results:
        if r["status"] == "failed":
            parts.append(f"{r['label']}: FAILED ({r['error']})")
        elif r["status"] == "skipped_empty":
            parts.append(f"{r['label']}: skipped (no files)")
        elif r["mr_iid"]:
            parts.append(f"{r['label']}: !{r['mr_iid']}")
        else:
            parts.append(f"{r['label']}: {r['status']}")
    return ", ".join(parts)


# ── Legacy single-MR entry point ─────────────────────────────────────────────


async def push_to_gitlab(
    run: PhaseBRun,
    files: list[dict],
    db: Session,
) -> GitEvent:
    """Legacy entry point preserved for direct callers.

    Delegates to `push_to_gitlab_multi`; returns the FIRST repo's GitEvent so
    existing single-MR consumers (returning `branch_name`, `commit_sha`,
    `mr_url`, `mr_iid`) keep working. New REST endpoint should call
    `push_to_gitlab_multi` directly to get the full per-repo list.
    """
    multi_result = await push_to_gitlab_multi(run, files, db)
    if not multi_result["results"]:
        raise RuntimeError("push_to_gitlab: no repos to push to")

    # Find the GitEvent row that matches the first repo's branch (most
    # recent for this run). M-4 creates one GitEvent per repo, so we pick
    # the most-recent one for legacy display.
    git_event = (
        db.query(GitEvent)
        .filter(GitEvent.phase_b_run_id == run.id)
        .order_by(GitEvent.created_at.desc())
        .first()
    )
    if git_event is None:
        # Defensive — shouldn't happen because _push_one_repo always inserts.
        raise RuntimeError("push_to_gitlab: no GitEvent row was created")

    return git_event
