# Copyright 2026 National Payments Corporation of India
# SPDX-License-Identifier: MIT

"""API Registry — canonical store of UPI wire-API field constraints.

Two tables: api_messages (one per Req*/Resp* message) and api_fields (one per
tag/attribute with its documented constraints + per-source evidence JSON).
The TSD interface_spec field dictionaries are rendered deterministically from
these rows instead of re-generated by the LLM each run.

Idempotent + inspector-gated (safe to re-run).

Revision ID: 0110
Revises: 0109
"""
from alembic import op
import sqlalchemy as sa

revision = "0110"
down_revision = "0109"
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    tables = set(insp.get_table_names())

    if "api_messages" not in tables:
        op.create_table(
            "api_messages",
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column("api_name", sa.String(200), nullable=False, unique=True, index=True),
            sa.Column("direction", sa.String(20), nullable=False, server_default="other"),
            sa.Column("namespace", sa.String(500), nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("sample_xml", sa.Text(), nullable=True),
            sa.Column("source", sa.String(60), nullable=False, server_default="xsd_parse"),
            sa.Column("source_schema_path", sa.String(1000), nullable=True),
            sa.Column("status", sa.String(20), nullable=False, server_default="active"),
            sa.Column("introduced_by_change_id", sa.String(36), nullable=True),
            sa.Column("updated_by", sa.String(200), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            # Nullable to match TimestampMixin (set on update only, None on insert).
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )

    if "api_fields" not in tables:
        op.create_table(
            "api_fields",
            sa.Column("id", sa.String(36), primary_key=True),
            sa.Column("message_id", sa.String(36),
                      sa.ForeignKey("api_messages.id", ondelete="CASCADE"), nullable=False),
            sa.Column("parent_field_id", sa.String(36),
                      sa.ForeignKey("api_fields.id", ondelete="CASCADE"), nullable=True),
            sa.Column("position", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("depth", sa.Integer(), nullable=False, server_default="0"),
            sa.Column("tag_num", sa.String(30), nullable=True),
            sa.Column("xml_tag", sa.String(200), nullable=False),
            sa.Column("is_attribute", sa.Boolean(), nullable=False, server_default=sa.text("false")),
            sa.Column("xpath", sa.String(1000), nullable=False),
            sa.Column("message_item", sa.Text(), nullable=True),
            sa.Column("occurrence", sa.String(20), nullable=True),
            sa.Column("datatype", sa.String(60), nullable=True),
            sa.Column("length_rule", sa.String(200), nullable=True),
            sa.Column("mandatory", sa.String(5), nullable=True),
            sa.Column("condition_text", sa.Text(), nullable=True),
            sa.Column("rules_ref", sa.String(500), nullable=True),
            sa.Column("enum_values", sa.JSON(), nullable=True),
            sa.Column("constraint_sources", sa.JSON(), nullable=True),
            sa.Column("source", sa.String(60), nullable=False, server_default="xsd_parse"),
            sa.Column("status", sa.String(20), nullable=False, server_default="active"),
            sa.Column("introduced_by_change_id", sa.String(36), nullable=True),
            sa.Column("updated_by", sa.String(200), nullable=True),
            sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
            # Nullable to match TimestampMixin (set on update only, None on insert).
            sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        )
        op.create_index("ix_api_fields_message_id", "api_fields", ["message_id"])
        op.create_index("ix_api_fields_message_xpath", "api_fields", ["message_id", "xpath"], unique=True)


def downgrade():
    bind = op.get_bind()
    insp = sa.inspect(bind)
    tables = set(insp.get_table_names())
    if "api_fields" in tables:
        op.drop_table("api_fields")
    if "api_messages" in tables:
        op.drop_table("api_messages")
